  spring:
    application:
      name: Spring demo
    datasource:
      driver-class-name: org.h2.Driver
      password: ''
      url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
      username: tk

  logging:
    level:
      root: DEBUG